/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MLX90316_MISO.h"
#include "MLX90316_MISO_aliases.h"
#include "MLX90316_SCLK.h"
#include "MLX90316_SCLK_aliases.h"
#include "MLX90316_SPIM.h"
#include "MLX90316_SPIM_PVT.h"
#include "MLX90316_SS.h"
#include "MLX90316_SS_aliases.h"
#include "MLX90316_SS_ControlReg.h"
#include "LCD.h"
#include "SPIM_Clock.h"
#include "MLX90316_MOSI_DEBUG.h"
#include "MLX90316_MOSI_DEBUG_aliases.h"
#include "MLX90316_MISO_Comp.h"
#include "MLX90316_VDAC8.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"

/*[]*/

